### PR TITLE
 Improvement of invoice webhooks and model constants

### PR DESCRIPTION
**Pull request by alexstewartja**
This PR aims to:

- Create Webhook-related Exceptions
- Implement Invoice webhook request action (+ test case)
- Create missing constants specifically for:
  + Invoice exception statuses
  + Subscription schedules
  + Settlement statuses

### CODE REVIEW

**Comment by anbugal** [comment]
we'll look into it but there's no reason to delete existing tests

**Comment by alexstewartja** [comment]
Which is right. No idea how that crept in but it's clearly a rebase glitch. Fixed.

**Comment by alexstewartja** [comment]
Any updates on this @anbug?

**Comment by anbugal** [comment]
closing for not resolving the change requests

**Comment by alexstewartja** [comment]
@anbugal What change requests? The tests that were omitted from the primary commit were re-introduced in the following commit.

**Pull request closed without merging**
