### PR TITLE
Update yaml to allow v5

### PR DESCRIPTION
**Pull request by gmponos**

### CODE REVIEW

**Comment by anbugal** [comment]
Hi @gmponos 

Are you using the config file in yaml and have you test this change?
We will test it and merge once completed.


Thanks for your contribution.

**Comment by gmponos** [comment]
> Are you using the config file in yaml and have you test this change?

No I have not.. I was hoping that you will have some kind of CI that will indicate if this is a bad change or not...

**Comment by anbugal** [comment]
All changes should be tested even if having CI in place. One thing doesn't substitute the other.
Will test it and update soon.

**Comment by gmponos** [comment]
Hello, do we have any news on this?

**Review by anbugal — APPROVED** [review]
Thanks for your contribution, we have tested and approved the change

**Pull request merged**
