### PR TITLE
Add the ability to specify a proxy url to send requests through to bitpay

### PR DESCRIPTION
**Pull request by Porthorian**
It would be a nice addition to add the ability to support proxy urls via the bitpay wrapper here since guzzle does support the ability to proxy requests through.

Few key reasons on why I would like this to be merged in.

In some instances companies tend to have a heavy firewall, and will result into having to proxy 3rd party requests to a proxy server do to compliance reasons in us knowing where the traffic comes from.

bitpay.com has consistently changed the ips whether it is via cloudflare or not. We no longer can whitelist the ip address through to our firewall to allow outbound traffic to it.

### CODE REVIEW

**Comment by anbugal** [comment]
Hi @Porthorian 

Your code looks good and we will be happy to merge it as soon as we go through it.
Thank you for your contribution.


Regards.

**Comment by Porthorian** [comment]
@anbugal 
I have a proxy server if you would like to use it for testing. Its currently configured to allow requests to test.bitpay.com. The security of the server is really not a concern as its just a dummy server with squid on it.

**Comment by Porthorian** [comment]
Also worth noting we have been running these changes in production now for the past 15 days

**Comment by Porthorian** [comment]
@anbugal You wouldn't happen to know what the bitpay rate limit is off the top of your head would you? We are just curious over here what it actually is, as we can't seem to find any documentation regarding the bitpay ratelimit for the api.

**Comment by anbugal** [comment]
Hi @Porthorian the rate limit would be enough for a normal use of the services, we would not disclose that type of information.

**Pull request merged**
