### PR TITLE
Test enhancement

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Using the `php-7.3` and `php-7.4` versions during Travis CI build.
- Add `composer install` and `vendor/bin/phpunit` commands during Travis CI build.
- Add correct namespace to load classes automatically with `PSR-4` autoloading.
- It seems that these cached dependencies have been outdated and it should update these cached dependencies via `composer update` command.

### CODE REVIEW

**Comment by anbugal** [comment]
The tests on this repository are mostly functional mostly which are not elegible for automated testing.
All changes are tested properly before being deployed.

**Comment by peter279k** [comment]
Hi @anbugal, thanks for your reply.

These test are not automated, and how to verify these approaches are correct?

I think some of test approaches are not correct and they need to be improved...

**Comment by anbugal** [comment]
@peter279k "These test are not automated" because "The tests on this repository are mostly functional"
Could you give an example of those "some of test approaches are not correct and they need to be improved"?

This library implements all features available on the BitPay's API and they "are tested properly before being deployed" even when they come from non official contributors.

Thanks for your contribution.

**Comment by peter279k** [comment]
> @peter279k "These test are not automated" because "The tests on this repository are mostly functional"
> Could you give an example of those "some of test approaches are not correct and they need to be improved"?
> 
> This library implements all features available on the BitPay's API and they "are tested properly before being deployed" even when they come from non official contributors.
> 
> Thanks for your contribution.

@anbugal, thanks for your reply. And I can create another PR about this I mention.

I think these tests are not automated, and we can consider removing `.travis.yml`  because this is not necessary on this repository.

**Pull request closed without merging**
